# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true
# Enables Gradle Build Cache
org.gradle.caching=true
# Enables parallel execution
org.gradle.parallel=true
# Allow non-ASCII project path on Windows
android.overridePathCheck=true
systemProp.file.encoding=UTF-8
systemProp.sun.jnu.encoding=UTF-8

